// Code generated by "stringer -type=DiagDirection"; DO NOT EDIT.

package util

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[N-0]
	_ = x[NE-1]
	_ = x[E-2]
	_ = x[SE-3]
	_ = x[S-4]
	_ = x[SW-5]
	_ = x[W-6]
	_ = x[NW-7]
}

const _DiagDirection_name = "NNEESESSWWNW"

var _DiagDirection_index = [...]uint8{0, 1, 3, 4, 6, 7, 9, 10, 12}

func (i DiagDirection) String() string {
	if i < 0 || i >= DiagDirection(len(_DiagDirection_index)-1) {
		return "DiagDirection(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DiagDirection_name[_DiagDirection_index[i]:_DiagDirection_index[i+1]]
}
